SELECT COUNTRY.CONTINENT,
FLOOR(AVG(CITY.POPULATION)) AS NEW_POPULATION -- NEW COLUMN
-- FLOOR (التقريب لإكبر عدد صحيح قبل العدد الناتج) X CEILING (اكبرعدد صحيح بعد العدد الناتج)
FROM COUNTRY
JOIN CITY
ON CITY.COUNTRYCODE=COUNTRY.CODE
GROUP BY CONTINENT ;